### ISSUE TITLE
Twitch Crash

### ISSUE THREAD

**Issue by reapazor** [dotBunny/JARVIS#63]
2017/08/15 13:30:04 [Spotify]   New track detected: Grandtheft, Hedspin - Mobbin
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x42f8754]

goroutine 179 [running]:
_/Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/modules/twitch.(*Module).pollFollowers(0xc420170000, 0x101)
        /Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/modules/twitch/polling.go:65 +0x924
_/Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/modules/twitch.(*Module).Poll(0xc420170000, 0xc4204f1c01)
        /Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/modules/twitch/polling.go:38 +0x34
_/Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/modules/twitch.(*Module).loop(0xc420170000)
        /Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/modules/twitch/polling.go:30 +0x5e
created by _/Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/modules/twitch.(*Module).setupPolling
        /Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/modules/twitch/polling.go:22 +0x1a5
MattBook:jarvis reapazor$

**Comment by reapazor** [comment]
Fixed in 458cd4e781594c958313928c6fa52cd3ef0235bf
