### ISSUE TITLE
Discord Crash

### ISSUE THREAD

**Issue by reapazor** [dotBunny/JARVIS#64]
If unable to get credentials crashes, not nicely

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42c5ed2]

goroutine 20 [running]:
_/Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/core.(*DiscordCore).Connect(0xc4200fc280)
        /Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/core/discord.go:123 +0x182
_/Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/core.HireJarvis(0x5995a52d)
        /Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/core/base.go:87 +0x384
main.onReady.func3()
        /Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/jarvis.go:63 +0x6d
created by main.onReady
        /Users/reapazor/Repositories/dotBunny/JARVIS/src/jarvis/jarvis.go:97 +0x10b

**Comment by reapazor** [comment]
This was an requirements crash, if discord isn't there things need to die nicely. IT now fails ahead of this.
